apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bootc-operator
    app.kubernetes.io/managed-by: kustomize
  name: daemon-role
rules:
- apiGroups:
  - node.bootc.dev
  resources:
  - bootcnodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - node.bootc.dev
  resources:
  - bootcnodes/status
  verbs:
  - get
  - update
  - patch
