---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bootc.dev
  resources:
  - bootcnodepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bootc.dev
  resources:
  - bootcnodepools/finalizers
  verbs:
  - update
- apiGroups:
  - bootc.dev
  resources:
  - bootcnodepools/status
  - bootcnodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bootc.dev
  resources:
  - bootcnodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
