---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - bootc.dev
  resources:
  - bootcnodepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bootc.dev
  resources:
  - bootcnodepools/finalizers
  verbs:
  - update
- apiGroups:
  - bootc.dev
  resources:
  - bootcnodepools/status
  verbs:
  - get
  - patch
  - update
