apiVersion: bootc.dev/v1alpha1
kind: BootcNodePool
metadata:
  labels:
    app.kubernetes.io/name: bootc-operator
    app.kubernetes.io/managed-by: kustomize
  name: bootcnodepool-sample
spec:
  # TODO(user): Add fields here
